version: '3'
services:
  app:
    build: .
    ports:
      - "${SERVER_PORT}:8765"
    environment:
      - DEBUG=${DEBUG}
      - MQTT_BROKER=${MQTT_BROKER}
      - MQTT_PORT=${MQTT_PORT}
      - MQTT_TOPIC=${MQTT_TOPIC}
      - SERVER_ADDRESS=${SERVER_ADDRESS}
      - SERVER_PORT=${SERVER_PORT}
